### ISSUE TITLE
Consider changing `transformers` props of a Builder to an array

### ISSUE THREAD

**Issue by pa3** [commercetools/test-data#25]
That's just a tiny neat-pick, feel free to close this issue right away if you don't like it. =) 

As transformation type is passed as a first param to `Transformer` now anyways, we can probably change transformers prop to be an array, so that instead of:

```js
const transforms = {
  graphql: Transformer<Model, ModelTransformed>('graphql', {
    replaceFields: ({ fields }) => doYourGraphqlStuffHere(fields),
  }),
  rest: Transformer<Model, ModelTransformed>('rest', {
    replaceFields: ({ fields }) => doYourRestStuffHere(fields),
  }),
}
```

We will have:

```js
const transforms = [
  Transformer<Model, ModelTransformed>('graphql', {
    replaceFields: ({ fields }) => doYourGraphqlStuffHere(fields),
  }),
  Transformer<Model, ModelTransformed>('rest', {
    replaceFields: ({ fields }) => doYourRestStuffHere(fields),
  }),
]
```

A bit less need for typing and less possibility to mess things.

**Comment by tdeekens** [comment]
Doesn't this open the door for having multiple transforms of the same type?

**Comment by adnasa** [comment]
what can be considered is that we register the name of the transformer (e.g `graphql`) and the next transformer of the same name.

Also, I think it's a mistake from dev to register multiple transformers of the same name, but this is my opinion

**Comment by tdeekens** [comment]
> Also, I think it's a mistake from dev to register multiple transformers of the same name, but this is my opinion

Yes but now we can sort of type check and/or lint it. With the an array it might still be possible but harder at least.

**Comment by emmenko** [comment]
Thanks for suggesting this.

As I was migrating the core package to make it type safe, this was an option I considered (to have the transformers as a list).
Actually I was thinking more of something like `GraphqlTransformer`, `RestTransformer`, etc. so the transformer instance itself was kind of opinionated.

Eventually I decided to keep it "simpler" to just a map object, which in turns makes the typing a bit easier.

For example, this is where having a map makes the implementation easier:
https://github.com/commercetools/test-data/blob/7f217ce95487e854f3ed8b48730774bedd679aad/core/src/builder.ts#L122-L137

However, if we find a better API we can for sure change things. We just need to consider different aspects.

**Comment by pa3** [comment]
Thanks for clarifying this. Indeed, probably left leave it as it is.
